### PR TITLE
add github action based ci

### PR DESCRIPTION
**Pull request by tfoote**
Leverage github actions-ros-ci to run general build and test the packages from source.

### CODE REVIEW

**Comment by tfoote** [comment]
I don't see the CI running automatically. I'm not sure if it's giving a button for maintainers to approve the workflow trigger potentially. The results from my branch are here: https://github.com/tfoote/rosidl_typesupport_protobuf/actions/runs/7171896607

**Comment by KerstinKeller** [comment]
@FlorianReimold didn't you need to be a member and not only contributor, to make CI related changes?

**Comment by FlorianReimold** [comment]
@KerstinKeller 

At this point this is only a file in a repository. Anybody can PR to it. There are only restrictions for actually executing the workflow scripts.
I will check what we have to configure to make the CI execute the workflow file, but probably we only have to merge it.

**Comment by tfoote** [comment]
On our repos we get a prompt like this to allow workflows from non-maintainers where you just have to allow the workflow manually after reviewing. The documentation link is here: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
image

**Comment by FlorianReimold** [comment]
Yes, we also get that, but I think the target repo (so this repo here) must have any GitHub Action Workflow configured. I merged the PR, so I think in the future we would get the same prompt.

**Comment by tfoote** [comment]
Oh, that's an interesting edge case that they don't catch in that security type of audit. But in good news it does appear to be working. The merged commit successfully ran CI: https://github.com/eclipse-ecal/rosidl_typesupport_protobuf/actions/workflows/basic_ci.yaml

**Pull request merged**
